packages:
    - 'packages/*'
    - 'apps/*'
    - 'tools/*'
    - 'examples/*'
    - 'play'
    - 'docs'

catalog:
    '@vitejs/plugin-vue': ^6.0.6
    '@vitejs/plugin-vue-jsx': ^5.1.5
    '@vue/shared': ^3.5.22
    '@vue/test-utils': ^2.4.6
    '@vueuse/core': 14.2.1
    vue-component-type-helpers: ^3.2.4
    vue: ^3.5.22

overrides:
    typescript: $typescript

peerDependencyRules:
    ignoreMissing:
        - vite
        - vue

shellEmulator: true
strictPeerDependencies: false
