packages:
    - 'packages/*'
    - 'apps/*'
    - 'tools/*'
    - 'examples/*'
    - 'play'
    - 'site'

shamefullyHoist: true
shellEmulator: true
sideEffectsCache: false
strictPeerDependencies: false
