/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/accordion/src/accordion.vue')['default']
    Aside: typeof import('./src/components/aside/aside.vue')['default']
    Breadcrumb: typeof import('./src/components/breadcrumb/src/Breadcrumb.vue')['default']
    BreadcrumbItem: typeof import('./src/components/breadcrumb/src/BreadcrumbItem.vue')['default']
    Button: typeof import('./src/components/button/src/button.vue')['default']
    Card: typeof import('./src/components/card/card.vue')['default']
    Checkbox: typeof import('./src/components/checkbox/checkbox.vue')['default']
    Container: typeof import('./src/components/container/container.vue')['default']
    Footer: typeof import('./src/components/footer/footer.vue')['default']
    Grid: typeof import('./src/components/grid/src/grid.vue')['default']
    GridItem: typeof import('./src/components/grid/src/gridItem.vue')['default']
    Guide: typeof import('./src/components/guide/src/Guide.vue')['default']
    Header: typeof import('./src/components/header/header.vue')['default']
    Icon: typeof import('./src/components/icon/icon.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    Main: typeof import('./src/components/main/main.vue')['default']
    Menu: typeof import('./src/components/menu/Menu.vue')['default']
    MenuItem: typeof import('./src/components/menu/MenuItem.vue')['default']
    Modal: typeof import('./src/components/modal/src/modal.vue')['default']
    Pagination: typeof import('./src/components/pagination/pagination.vue')['default']
    Progress: typeof import('./src/components/progress/Progress.vue')['default']
    Radio: typeof import('./src/components/radio/radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step: typeof import('./src/components/guide/src/Step.vue')['default']
    Table: typeof import('./src/components/table/table.vue')['default']
    TabPane: typeof import('./src/components/tabs/TabPane.vue')['default']
    Tabs: typeof import('./src/components/tabs/Tabs.vue')['default']
    Tag: typeof import('./src/components/tag/src/Tag.vue')['default']
    Tooltip: typeof import('./src/components/tooltip/tooltip.vue')['default']
    Tree: typeof import('./src/components/tree/Tree.vue')['default']
    TreeNode: typeof import('./src/components/tree/TreeNode.vue')['default']
    Uploader: typeof import('./src/components/uploader/Uploader.vue')['default']
    UploaderDragger: typeof import('./src/components/uploader/UploaderDragger.vue')['default']
    UploaderList: typeof import('./src/components/uploader/UploaderList.vue')['default']
  }
}
