/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AppMain: typeof import('./src/components/layout/AppMain.vue')['default']
    Bubble: typeof import('./src/components/widgets/Bubble.vue')['default']
    Fieldset: typeof import('./src/components/widgets/Fieldset.vue')['default']
    Firework: typeof import('./src/components/widgets/Firework.vue')['default']
    NotFound: typeof import('./src/components/layout/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WAside: typeof import('w-design-vue')['WAside']
    WBreadcrumb: typeof import('w-design-vue')['WBreadcrumb']
    WBreadcrumbItem: typeof import('w-design-vue')['WBreadcrumbItem']
    WButton: typeof import('w-design-vue')['WButton']
    WFooter: typeof import('w-design-vue')['WFooter']
    WHeader: typeof import('w-design-vue')['WHeader']
    WIcon: typeof import('w-design-vue')['WIcon']
    WLayout: typeof import('w-design-vue')['WLayout']
    WMain: typeof import('w-design-vue')['WMain']
    WMenu: typeof import('w-design-vue')['WMenu']
    WMenuItem: typeof import('w-design-vue')['WMenuItem']
    WModal: typeof import('w-design-vue')['WModal']
  }
}
